# Inserts a blank line between shell prompts
add_newline = true

[character]
# Character shown after success
success_symbol = '[ ](bold green)'
# Character shown after error
error_symbol = '[ ](bold red)'
